version: "3"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5817:5432
    expose:
      - "5817"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
