version: "3"
services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5817:5432
    expose:
      - "5817"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
